Repository kalkih/mini-media-player, pull requests merged in 2020-04, with the labels that each got.

#275 Options to hide previous and/or next playback controls #233
  README.md
  src/components/mediaControls.js
  src/const.js
Labels: enhancement

#274 Sync mute when sync_volume is enabled #262
  src/model.js
Labels: enhancement

#273 New tts entity_id parameter to target speaker group #268
  README.md
  src/components/tts.js
  src/main.js
Labels: enhancement

#272 Resume progress tracking when re-connected #269
  src/components/progress.js
Labels: bug

#271 Fixed tts text color when artwork is present #270
  src/components/tts.js
Labels: bug

#290 Remove deprecated updating step
  README.md
Labels: docs
