Repository kalkih/mini-media-player, pull requests merged in 2020-08, with the labels that each got.

#364 Fix webkit border radius issue #352
  src/style.js
Labels: bug

#331 New artwork type
  .babelrc
  package.json
  src/components/mediaControls.js
  src/const.js
  src/main.js
  src/style.js
  src/utils/colorGenerator.js
Labels: enhancement

#370 Add Polish language
  src/translations.js
Labels: translation

#372 Fix broken artwork cover colors
  src/style.js
Labels: bug

#373 Fixed broken default artwork / icon
  src/main.js
Labels: bug

#371 Add French translation
  src/translations.js
Labels: translation

#375 Fixed broken default artwork
  src/main.js
Labels: bug

#380 Add translation support for master string
  src/components/groupItem.js
  src/translations.js
Labels: enhancement, translation

#381 Prevent jumping cover when transitioning artwork
  src/style.js
Labels: enhancement

#377 Add Hungarian translation strings
  src/translations.js
Labels: translation

#382 Add support for slider volume steps #365
  README.md
  src/components/mediaControls.js
Labels: enhancement

#390 Do not override default slider container color
  src/components/mediaControls.js
  src/style.js
Labels: bug

#391 Fix artwork not clearing after playback
  src/main.js
Labels: bug

#384 Correct TTS full form
  src/translations.js
Labels: enhancement

#392 Artowork relative url fallback
  src/main.js
Labels: bug

#396 Hungarian fixes
  src/translations.js
Labels: translation

#400 Add Ukrainian translation
  src/translations.js
Labels: translation

#405 Option to open url in new tab #227
  README.md
  src/utils/handleClick.js
Labels: enhancement

#406 Add ability to display volume level #289
  README.md
  src/components/mediaControls.js
  src/const.js
Labels: enhancement
