Repository kalkih/mini-media-player, pull requests merged in 2020-12, with the labels that each got.

#449 Fix artwork fallback
  src/main.js
Labels: bug

#456 Add README mention for Nabu Casa, which apparently works
  README.md
Labels: docs

#459 Fix checkbox label layout
  src/components/checkbox.js
Labels: bug

#458 Support for alternative current entity for groups
  README.md
  src/const.js
  src/main.js
  src/model.js
Labels: enhancement

#461 Update README.md
  README.md
Labels: docs
