Repository kalkih/mini-media-player, pull requests merged in 2021-11, with the labels that each got.

#564 Fix icon valign
  src/sharedStyle.js
Labels: enhancement

#570 Add chinese translations
  src/translations.js
Labels: translation

#569 Add tts platform: service
  README.md
  src/components/tts.js
Labels: enhancement

#576 (fix) Default jump_amount before destructure
  src/utils/config.js
Labels: bug
