Repository kalkih/mini-media-player, pull requests merged in 2021-07, with the labels that each got.

#521 Do not increment progress if player isn't playing
  src/model.js
Labels: bug

#526 Clarify which section of configuration.yaml to edit
  README.md
Labels: docs

#525 Added support for the new default grouping functionality
  README.md
  src/const.js
  src/model.js
  src/utils/config.js
Labels: enhancement
