Repository kalkih/mini-media-player, pull requests merged in 2022-05, with the labels that each got.

#651 Update usage examples
  README.md
Labels: docs

#656 Adjust for breaking Sonos change in HA 2022.5 (TS version)
  src/model.ts
Labels: enhancement

#660 icon_image to fit full height of entity__icon
  src/main.ts
Labels: bug

#667 Fix attribute assignment
  src/model.ts
Labels: bug

#668 Fix vibrant for rollup build
  rollup.config.dev.js
  rollup.config.js
  src/utils/colorGenerator.js
Labels: bug

#674 Adjust path to resources config page
  README.md
Labels: docs

#675 Update HACS URL
  README.md
Labels: docs
